### ISSUE TITLE
请问这种部署方式如何修改配置文件呢

### ISSUE THREAD

**Issue by zuriyd** [jinfeijie/yapi#19]
我想挂载配置目录出来可以修改 但是启动会报错
mv: cannot move '/home/config.json' to '/home/vendors/config.json': Device or resource busy

**Comment by jinfeijie** [comment]
![image](https://user-images.githubusercontent.com/8290380/74084563-45da0300-4aab-11ea-9377-83702431f93b.png)
在目录下面有个config.json，直接修改这个就好了
