### ISSUE TITLE
部署失败了

### ISSUE THREAD

**Issue by LL3706** [jinfeijie/yapi#21]
[
![image](https://user-images.githubusercontent.com/22722591/78685394-46b0d900-7924-11ea-81fe-2e0327dfa012.png)
](url)
[
![image](https://user-images.githubusercontent.com/22722591/78685575-82e43980-7924-11ea-9e2e-3a6a014b23fd.png)
](url)
这个原因是什么造成的，请大佬执教下

**Comment by jinfeijie** [comment]
你执行的命令似乎是错误的。
能贴上你是如何启动项目的代码么？

**Comment by LL3706** [comment]
docker-compose up -d

**Comment by jinfeijie** [comment]
https://travis-ci.org/github/jinfeijie/yapi/jobs/647633933

执行了一次CI，无法复现问题

**Comment by LL3706** [comment]
大佬，我查了资料，这个错误是指容器镜像格式错误，意思就是说这个用的是X86的镜像，需要替换成ARM镜像，现在问题是有没有ARM的镜像

**Comment by jinfeijie** [comment]
https://github.com/jinfeijie/yapi/blob/master/docker-compose.yml#L4

注释掉第四行代码，打开第五行的注释

再执行

**Comment by LL3706** [comment]
我试了一下，还是不行，我的服务器是：规格是kc 镜像是arm，https://bbs.huaweicloud.com/forum/thread-26434-1-1.html
[
![image](https://user-images.githubusercontent.com/22722591/78863093-5edf4000-7a6b-11ea-99df-3928cb2febe1.png)
](url)

**Comment by jinfeijie** [comment]
看样子是node的基础镜像不支持你的平台，你可以切换一下支持的node基础镜像。在已经修改的基础上
https://github.com/jinfeijie/yapi/blob/master/Dockerfile#L1
替换第一行
前往dockerhub找到支持你的平台的node基础镜像，然后`docker-compose up`

**Comment by LL3706** [comment]
> 看样子是node的基础镜像不支持你的平台，你可以切换一下支持的node基础镜像。在已经修改的基础上
> https://github.com/jinfeijie/yapi/blob/master/Dockerfile#L1
> 替换第一行
> 前往dockerhub找到支持你的平台的node基础镜像，然后`docker-compose up`

[
![image](https://user-images.githubusercontent.com/22722591/78866553-27c05d00-7a72-11ea-9943-86dcc98f850d.png)
](url)只改node的版本号就行吗

**Comment by jinfeijie** [comment]
换成支持你平台的就可以

**Comment by LL3706** [comment]
> 换成支持你平台的就可以

我在dockerHub 上没有找到我的平台的镜像，能不能用常规方法安装node, 再用docker-compose 安装yapi, Dockerfile 要怎么修改，docker-compose.yml 还要修改吗，求指导下

**Comment by LL3706** [comment]
> 换成支持你平台的就可以

我把node 版本改了，报错了
[
![image](https://user-images.githubusercontent.com/22722591/78998179-a0aadc00-7b7a-11ea-86cb-9fd209e6ce89.png)
](url)

**Comment by jinfeijie** [comment]
这些要求你有一定的docker基础，建议更换通用的宿主机系统
