### ISSUE TITLE
尝试自己构建镜像

### ISSUE THREAD

**Issue by zhangqinzhong** [jinfeijie/yapi#28]
mac 
版本 1.9.3
git clone 了本工程。
修改config.json 如下
![configjson](https://user-images.githubusercontent.com/42922131/125881864-4758eeb1-3e38-47fd-9ee7-d13141d064be.png)

docker-compose.yml 如下
![image](https://user-images.githubusercontent.com/42922131/125881980-6b992335-daa2-4cb8-9f8c-155742578bb9.png)

尝试 docker-compose up 

![image](https://user-images.githubusercontent.com/42922131/125882048-e15b4c52-3e48-4401-9e59-e9262a3fd62c.png)

想问下是什么问题。已经参考文档 创建了network：docker network create back-net

**Comment by jinfeijie** [comment]
你好，yapi和mongo是两个独立的容器。
127.0.0.1是本地的回环ip。
yapi连接mongo需要设置成mongo的ip。
图一，`db.servername`中的`127.0.0.1`直接改成`mongo`可以解决掉这个问题
@fslover
