### ISSUE TITLE
升级到v1.9.3

### ISSUE THREAD

**Issue by wongkunkun** [jinfeijie/yapi#29]
目前还没有升级到v1.9.3
自己修改版本好为v1.9.3 build镜像，运行的时候会报错：
yapi     | http://registry.npm.taobao.org/yapi-vendor/download/yapi-vendor-1.9.3.tgz
yapi     | Error:  Response code 404 (Not Found)
这个问题自己可以处理吗，或者希望能够支持1.9.3版本

**Comment by jinfeijie** [comment]
你好，官方npm仓库中最新的版本是1.9.2
`https://www.npmjs.com/package/yapi-vendor`

**Comment by jinfeijie** [comment]
1.9.3联系开发人员暂无回复。
建议按照ReadMe中的方案先处理一下

**Comment by jinfeijie** [comment]
@wongkunkun done

**Comment by xc2f** [comment]
![image](https://user-images.githubusercontent.com/11835233/215987249-f2be0cde-fecd-4b7f-afd9-b8f2251f3438.png)

1.9.3不能下了，1.9.2可以
