### ISSUE TITLE
请问一下部署完成后管理员账号密码是什么？

### ISSUE THREAD

**Issue by dengfan2018** [jinfeijie/yapi#34]
docker-compose.yaml 中配置的 ADMIN_EMAIL 对应的账号无法登录。
不知道如何获取管理员账号，个人注册的账号之间无法管理项目成员。

![image](https://user-images.githubusercontent.com/40187266/154776211-e86f55b8-84b0-4bca-96bc-f88eb4b13c04.png)

**Comment by jinfeijie** [comment]
ADMIN_EMAIL初始密码是 ymfe.org

**Comment by dengfan2018** [comment]
感谢解答，感谢你的这个项目，很方便就构建起来了。
