### ISSUE TITLE
配置文件没有映射到本机，怎么修改配置呢

### ISSUE THREAD

**Issue by youmikuang** [jinfeijie/yapi#35]
我加了一个本地映射到home 文件就报错了，怎么更改配置文件呢？？？

**Comment by youmikuang** [comment]
我看到历史issue 中有相似回答，但是我用的 docker-compose 启动的 应该改哪个目录的配置

**Comment by jinfeijie** [comment]
@youmikuang 你修改后的发出来看看

**Comment by youmikuang** [comment]
报错内容
<img width="607" alt="image" src="https://user-images.githubusercontent.com/16145443/156531434-1fe75d4d-b3f4-441e-be04-2a1ab236043b.png">

设置的目录映射。如果不映射到 /home 下是没办法修改配置文件的吧？？？
<img width="457" alt="image" src="https://user-images.githubusercontent.com/16145443/156531492-9255dbdf-ef19-4e20-ba2c-6975d034291b.png">

**Comment by jinfeijie** [comment]
`~/docker/config/config.json:/home/config.json`
把config.json放到你电脑的`~/docker/config/`目录里。再在volumes再新增一个目录引射，
`~/docker/config/config.json:/home/config.json`

你试试看


> 报错内容 <img alt="image" width="607" src="https://user-images.githubusercontent.com/16145443/156531434-1fe75d4d-b3f4-441e-be04-2a1ab236043b.png">
> 
> 设置的目录映射。如果不映射到 /home 下是没办法修改配置文件的吧？？？ <img alt="image" width="457" src="https://user-images.githubusercontent.com/16145443/156531492-9255dbdf-ef19-4e20-ba2c-6975d034291b.png">

**Comment by youmikuang** [comment]
> 
不行，报错了 仅仅只能文件夹映射。
 ⠿ Container yapi   Starting                                                                                                                                                   1.9s
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/Users/kj/docker/docs/yapi/config.json" to rootfs at "/home/config.json" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type、


话说 /home/config.json 是不是 yapi 的配置文件呢？？

**Comment by jinfeijie** [comment]
是的，这是配置文件。
可以直接把自己的配置文件放进去，然后把https://github.com/jinfeijie/yapi/blob/master/entrypoint.sh&nbsp;里面的sed 开头的那几行注释掉



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: youmikuang ***@***.***&gt;
发送时间: 2022年3月3日 17:19
收件人: jinfeijie/yapi ***@***.***&gt;
抄送: fj jin ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [jinfeijie/yapi] 配置文件没有映射到本机，怎么修改配置呢 (Issue #35)





   
不行，报错了 仅仅只能文件夹映射。
 ⠿ Container yapi   Starting                                                                                                                                                   1.9s
 Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/Users/kj/docker/docs/yapi/config.json" to rootfs at "/home/config.json" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type、
 
话说 /home/config.json 是不是 yapi 的配置文件呢？？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by youmikuang** [comment]
我还是本地安装了，不用 docker 了。 感谢~
