### ISSUE TITLE
版本不对以及部署完之后管理员帐号无法登录

### ISSUE THREAD

**Issue by michaeljia2021** [jinfeijie/yapi#36]
1.version设置为1.9.3，但部署完之后打开页面显示是1.9.1

2.admin email设置成我自己的邮箱，但装好了之后用邮箱登录时始终提示我该用户不存在。只能自己单独注册用户访问，这个管理员帐号有什么特殊权限呢？可以不用么

**Comment by jinfeijie** [comment]
> 1.version设置为1.9.3，但部署完之后打开页面显示是1.9.1
> 
> 2.admin email设置成我自己的邮箱，但装好了之后用邮箱登录时始终提示我该用户不存在。只能自己单独注册用户访问，这个管理员帐号有什么特殊权限呢？可以不用么

麻烦提供一下你的启动文件和配置。
管理员可以操作别人的项目

**Comment by hoysoft** [comment]
一样问题，没办法用，换了几个邮箱都不行，docker-compose 所有配置都没有做修改，除了邮箱

**Comment by jinfeijie** [comment]
> 一样问题，没办法用，换了几个邮箱都不行，docker-compose 所有配置都没有做修改，除了邮箱

@hoysoft @michaeljia2021 已经修复

1.9.3的版本似乎被删除了，现在最新版本为1.10.2，建议使用最新版本


<img width="1247" alt="image" src="https://user-images.githubusercontent.com/8290380/159127181-04edba41-981c-4f14-9af0-bd5ea14c2728.png">

**Comment by michaeljia2021** [comment]
@jinfeijie 

更新version为1.10.2之后yapi容器启动报错

[devopsadmin@xspl62t999t ~]$ sudo docker logs 87f754
wait-for-it.sh: waiting 120 seconds for mongo:27017
wait-for-it.sh: mongo:27017 is available after 1 seconds
当前安装版本： 1.10.2
连接数据库成功!
开始下载平台文件压缩包...
http://registry.npm.taobao.org/yapi-vendor/download/yapi-vendor-1.10.2.tgz
Error:  Redirected 10 times. Aborting.
internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module '/home/vendors/server/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by michaeljia2021** [comment]
试了下，下载了新的镜像之后，改成原来的1.9.3或者1.9.1也不行了，报得是一样的错，启动不了

**Comment by jinfeijie** [comment]
> 开始下载平台文件压缩包...
> http://registry.npm.taobao.org/yapi-vendor/download/yapi-vendor-1.10.2.tgz
> Error: Redirected 10 times. Aborting.

```
开始下载平台文件压缩包...
http://registry.npm.taobao.org/yapi-vendor/download/yapi-vendor-1.10.2.tgz
Error: Redirected 10 times. Aborting.
```

看去像registry.npm.taobao.org访问不通。需要你确认一下是否能访问这个镜像地址

@michaeljia2021

**Comment by jinfeijie** [comment]
可以注释掉下面这行代码的，把镜像加速去掉
https://github.com/jinfeijie/yapi/blob/master/Dockerfile#L22

再自己本地构建镜像，第4行注释掉，第5行的注释去掉
https://github.com/jinfeijie/yapi/blob/master/docker-compose.yml#L4-L5

**Comment by jinfeijie** [comment]
我开了一台测试机器，可以上去验证一下。
```
139.59.121.29
root
ynsJHbBsSr64ViZp
```

需要重新拉取最新的docker镜像

http://139.59.121.29:3000
账号：test@test.cn
密码：ymfe.org

@michaeljia2021

**Comment by michaeljia2021** [comment]
@jinfeijie 

我这台服务器是要通过代理上网的，我已经在docker-compose中加入了代理，之前那个版本的yapi镜像加入代理之后可以正常运作，这个版本的镜像加了代理还是不行，下面是我修改过的配置

    container_name: yapi
    environment:
      - VERSION=1.10.2
      - LOG_PATH=/tmp/yapi.log
      - HOME=/home
      - PORT=3000
      - ADMIN_EMAIL=test@test.com
      - DB_SERVER=mongo
      - DB_NAME=yapi
      - DB_PORT=27017
      - HTTP_PROXY=http://10.33.25.67:3128
      - HTTPS_PROXY=http://10.33.25.67:3128
      - NO_PROXY=127.0.0.1

**Comment by jinfeijie** [comment]
但是你的这个配置两个变量并不会起作用，这两个代理需要加到docker里面，而不是为这个容器加代理。可以搜索一下docker配置代理



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: michaeljia2021 ***@***.***&gt;
发送时间: 2022年3月22日 00:16
收件人: jinfeijie/yapi ***@***.***&gt;
抄送: fj jin ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [jinfeijie/yapi] 版本不对以及部署完之后管理员帐号无法登录 (Issue #36)





 
@jinfeijie
 
我这台服务器是要通过代理上网的，我已经在docker-compose中加入了代理，之前那个版本的yapi镜像加入代理之后可以正常运作，这个版本的镜像加了代理还是不行，下面是我修改过的配置
 container_name: yapi environment:   - VERSION=1.10.2   - LOG_PATH=/tmp/yapi.log   - HOME=/home   - PORT=3000   - ***@***.***   - DB_SERVER=mongo   - DB_NAME=yapi   - DB_PORT=27017   - HTTP_PROXY=http://10.33.25.67:3128   - HTTPS_PROXY=http://10.33.25.67:3128   - NO_PROXY=127.0.0.1

**Comment by michaeljia2021** [comment]
@jinfeijie 

之前就是我提这个问题的时候用得那个yapi镜像版本，我就是这样设置的，下载没问题，proxy设置能起作用。
现在这个版本我就是把yml配置里的version换成了1.10.2，其它配置都是一样的，跑起来之后就不起作用了，而且我现在是yml和.docker/config.json里都设置了代理，用docker inspect yapi 查看，显示如下，yml和config.json里配置的proxy都写进去了
"Config": {
            "Hostname": "5aa11cb10a31",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "http_proxy=http://10.33.25.67:3128",
                "LOG_PATH=/tmp/yapi.log",
                "HOME=/home",
                "PORT=3000",
                "DB_PORT=27017",
                "HTTPS_PROXY=http://10.33.25.67:3128",
                "NO_PROXY=127.0.0.1",
                "DB_NAME=yapi",
                "no_proxy=localhost,127.0.0.1",
                "ADMIN_EMAIL=test@test.com",
                "DB_SERVER=mongo",
                "VERSION=1.10.2",
                "HTTP_PROXY=http://10.33.25.67:3128",
                "https_proxy=http://10.33.25.67:3128",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin/

**Comment by jinfeijie** [comment]
保留.docker/config.json里面的代理就可以了。
镜像删掉重新拉。实在不行，我给你重新做个镜像。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: michaeljia2021 ***@***.***&gt;
发送时间: 2022年3月22日 10:29
收件人: jinfeijie/yapi ***@***.***&gt;
抄送: fj jin ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [jinfeijie/yapi] 版本不对以及部署完之后管理员帐号无法登录 (Issue #36)

**Comment by michaeljia2021** [comment]
删掉了，还是不行，之前那个镜像没tag么？貌似只有latest能下载，但之前那个确实加了代理可以用的，这会是哪里的问题呢

**Comment by jinfeijie** [comment]
@michaeljia2021

附件`文件.zip`里面有两个文件，你覆盖一下。

复制`mongodb.zip`里面的数据到`~/data/yapi/mongodb`里面。

docker-compose up 启动

登陆管理员账号`me@jinfeijie.cn`，密码`ymfe.org`，修改成你自己的账号和密码

[mongodb.zip](https://github.com/jinfeijie/yapi/files/8321307/mongodb.zip)


[文件.zip](https://github.com/jinfeijie/yapi/files/8321315/default.zip)

**Comment by michaeljia2021** [comment]
@jinfeijie 

这次启动正常了，但是用管理员帐户登录不了，自己注册也不行，yapi容器日志如下

wait-for-it.sh: waiting 120 seconds for mongo:27017
wait-for-it.sh: mongo:27017 is available after 1 seconds
log: -------------------------------------swaggerSyncUtils constructor-----------------------------------------------
log: 服务已启动，请打开下面链接访问:
http://127.0.0.1:3000/
error: MongoTimeoutError: Server selection timed out after 30000 ms, mongodb Authentication failed
(node:21) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
    at /home/vendors/exts/yapi-plugin-advanced-mock/server.js:24:38
(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
log: mongodb load success...
(node:21) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
    at /home/vendors/exts/yapi-plugin-statistics/server.js:12:38
(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
    at /home/vendors/exts/yapi-plugin-wiki/server.js:7:38
(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by jinfeijie** [comment]
你的mongo连不上，config.json改成你自己的

**Comment by michaeljia2021** [comment]
@jinfeijie 
这次好了，多谢。
