### ISSUE TITLE
部署完毕之后,不能添加用户呀?

### ISSUE THREAD

**Issue by lisqorz** [jinfeijie/yapi#38]
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/42998845/161188275-73c72383-989d-4eb6-b053-56999e4c7a92.png">

**Comment by jinfeijie** [comment]
> <img alt="image" width="1502" src="https://user-images.githubusercontent.com/42998845/161188275-73c72383-989d-4eb6-b053-56999e4c7a92.png">

注册

**Comment by jinfeijie** [comment]
http://139.59.121.29:3000/
账号：test@test.cn
密码：ymfe.org


http://139.59.121.29:3000/login

**Comment by lisqorz** [comment]
在哪里调整角色权限呀?

**Comment by lisqorz** [comment]
我记得之前在这里可以设置的

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/42998845/161188997-1b4e835c-508a-42cb-b084-306fea30e196.png">

**Comment by lisqorz** [comment]
搞定了,有一些操作方式变化了
