### ISSUE TITLE
镜像里mongo的默认用户名密码是什么？

### ISSUE THREAD

**Issue by yx91490** [jinfeijie/yapi#4]

**Comment by jinfeijie** [comment]
@yx91490 默认没有密码

**Comment by xzyk** [comment]
因为默认没有密码。我刚部署就被入侵了
All your data is a backed up. You must pay 0.05 BTC to 1Kz6v4B5CawcnL8jrUvHsvzQv5Yq4fbsSv 48 hours for recover it. After 48 hours expiration we will leaked and exposed all your data. In case of refusal to pay, we will contact the General Data Protection Regulation, GDPR and notify them that you store user data in an open form and is not safe. Under the rules of the law, you face a heavy fine or arrest and your base dump will be dropped from our server! You can buy bitcoin here, does not take much time to buy https://localbitcoins.com or https://buy.moonpay.io/ After paying write to me in the mail with your DB IP: rambler+1x3n@onionmail.org and/or mariadb@mailnesia.com and you will receive a link to download your database dump.

**Comment by jinfeijie** [comment]
@xzyk 

> 因为默认没有密码。我刚部署就被入侵了 All your data is a backed up. You must pay 0.05 BTC to 1Kz6v4B5CawcnL8jrUvHsvzQv5Yq4fbsSv 48 hours for recover it. After 48 hours expiration we will leaked and exposed all your data. In case of refusal to pay, we will contact the General Data Protection Regulation, GDPR and notify them that you store user data in an open form and is not safe. Under the rules of the law, you face a heavy fine or arrest and your base dump will be dropped from our server! You can buy bitcoin here, does not take much time to buy https://localbitcoins.com or https://buy.moonpay.io/ After paying write to me in the mail with your DB IP: [rambler+1x3n@onionmail.org](mailto:rambler+1x3n@onionmail.org) and/or [mariadb@mailnesia.com](mailto:mariadb@mailnesia.com) and you will receive a link to download your database dump.

如果mongo是在内网情况下，可以确认不是通过mongo直接进行入侵的。
mongo作为yapi依赖的组件，可以独立部署带密码的mongo服务，yapi通过密码连接上mongo。但是就算有密码，也不建议对外暴露mongo，使mongo可以在公网直接连接。

另外，比特币勒索本身就是违法的，不建议支付比特币进行数据赎回。建议首先考虑数据恢复。
