### ISSUE TITLE
这里面有病毒么？

### ISSUE THREAD

**Issue by qsirwyk** [jinfeijie/yapi#43]
![WechatIMG298](https://github.com/jinfeijie/yapi/assets/107340650/000dc0aa-9704-423e-880a-95e49e47fa86)

**Comment by jinfeijie** [comment]
你的服务看去正在被人入侵，及时检查。
低版本有沙箱越权漏洞，需要升级到1.9.3+版本。https://github.com/YMFE/yapi/commit/3de66a6187849af509172103847a442fb8608864
注意备份数据库，以免丢失数据。

@qsirwyk
