### ISSUE TITLE
部署完了不能公网访问

### ISSUE THREAD

**Issue by jiangtao69039** [jinfeijie/yapi#8]
部署在阿里云实例上
部署完成后不能公网访问
似乎把docker-compose.yml中端口映射的127.0.0.1:3000:3000改成3000:3000就可以了

**Comment by jinfeijie** [comment]
@jiangtao69039 这个是一个安全策略，直接将服务暴露到公网不仅占用端口，而且会有未知风险。建议前面加一层网关类的服务。
如果真的有需求需要直接暴露出来，可以按你这么改。

后面的链接是如何用nginx代理后端服务的conf文件：[Nginx 配置](https://github.com/jinfeijie/yapi#nginx-%E9%85%8D%E7%BD%AE)

**Comment by PhageT2** [comment]
配置了Nginx 502，腾讯云轻量级服务器
