### ISSUE TITLE
使用docker部署，关闭注册的话可使用哪个变量开关？

### ISSUE THREAD

**Issue by mrxliu** [jinfeijie/yapi#9]
RT

**Comment by jinfeijie** [comment]
> RT

参考yapi官方文档

**Comment by mrxliu** [comment]
我意思是问，有没有 可修改变量 配置？类似ADMIN_EMAIL，能直接在docker-compose.yml里改

**Comment by mrxliu** [comment]
> > RT
> 
> 参考yapi官方文档

我意思是问，有没有 可修改变量 配置？类似ADMIN_EMAIL，能直接在docker-compose.yml里改

**Comment by jinfeijie** [comment]
> > > RT
> > 
> > 
> > 参考yapi官方文档
> 
> 我意思是问，有没有 可修改变量 配置？类似ADMIN_EMAIL，能直接在docker-compose.yml里改

这个没有。可以直接在config.json里面设置

docker-compose.ymal里面只设置了一些基础的配置参数

**Comment by mrxliu** [comment]
> > > > RT
> > > 
> > > 
> > > 参考yapi官方文档
> > 
> > 
> > 我意思是问，有没有 可修改变量 配置？类似ADMIN_EMAIL，能直接在docker-compose.yml里改
> 
> 这个没有。可以直接在config.json里面设置
> 
> docker-compose.ymal里面只设置了一些基础的配置参数

这个麻烦可以加上吗？毕竟配置改一下要重新打包挺麻烦

**Comment by jinfeijie** [comment]
> > > > > RT
> > > > 
> > > > 
> > > > 参考yapi官方文档
> > > 
> > > 
> > > 我意思是问，有没有 可修改变量 配置？类似ADMIN_EMAIL，能直接在docker-compose.yml里改
> > 
> > 
> > 这个没有。可以直接在config.json里面设置
> > docker-compose.ymal里面只设置了一些基础的配置参数
> 
> 这个麻烦可以加上吗？毕竟配置改一下要重新打包挺麻烦

可以。近期会加上
如果急用，你也可以提交一下merge请求
自动测试通过后，就会合并，自动构建新镜像

**Comment by mrxliu** [comment]
稍等
